### ISSUE TITLE
pyasn1 0.3.1 causes syncrepl-client to return no records

### ISSUE THREAD

**Issue by akkornel** [akkornel/syncrepl#18]
When running with pyasn1==0.3.1 (the latest available), syncrepl-client appears to work, but it doesn't show any records.

Example:

```
python3 /usr/local/bin/syncrepl-client ldaps://ldap-uatmaster.stanford.edu:636/cn=people,dc=stanford,dc=edu?uid,suprivilegegroup?base?uid=ljlgeek?bindname=GSSAPI uat-syncs
Data files will be stored here: uat-syncs
Refresh-only mode will be used
CLIENT SETUP START
BIND COMPLETE!
    WE ARE: dn:uid=ljlgeek,cn=accounts,dc=stanford,dc=edu
CLIENT SETUP COMPLETE!
CLIENT LOOP START
COOKIE CHANGED: rid=000,sid=064,csn=20170621020008.854439Z#000000#000#000000;20170816225047.962399Z#000000#064#000000;20170816125603.382427Z#000000#065#000000
REFRESH COMPLETE!
BEGIN DIRECTORY CONTENTS:
END DIRECTORY CONTENTS
CLIENT LOOP END
    Loop Result: False
CLIENT LOOP COMPLETE!
CLIENT EXIT START
CLIENT EXIT COMPLETE!
```

In the above example, one record should've been returned.

Credit to @ljl-geek for finding this.

**Comment by akkornel** [comment]
I've confirmed this affects 0.3.1 and 0.3.2.  Earlier versions are OK.  The lowest supported version should be 0.2.2, because that includes security fixes.

The test script at the following URL shows the problem:

https://gist.github.com/akkornel/3f3c302ef7271cf2d3958d65a4bd6f15

When run on a failing version, you'll see behavior like this:

```
Karls-Mac-Mini-9346:~ akkornel$ pip-3.6 install --user pyasn1==0.3.2
Requirement already satisfied: pyasn1==0.3.2 in ./Library/Python/3.6/lib/python/site-packages
Karls-Mac-Mini-9346:~ akkornel$ python3.6 ~/Downloads/pyasn1\ test.py 
pyasn1 version is 0.3.2
state is 1
uuid is e1d57f4e-234f-1035-97a2-4d5606180c6f
cookie is Traceback (most recent call last):
  File "/Users/akkornel/Downloads/pyasn1 test.py", line 52, in <module>
    print('cookie is', decoded_cookie)
  File "/Users/akkornel/Library/Python/3.6/lib/python/site-packages/pyasn1/type/univ.py", line 978, in __str__
    return self._value.decode(self.encoding)
  File "/Users/akkornel/Library/Python/3.6/lib/python/site-packages/pyasn1/type/base.py", line 207, in __getattr__
    raise error.PyAsn1Error('No value for "%s"' % attr)
pyasn1.error.PyAsn1Error: No value for "decode"
```

(Note, this problem appears in both python-ldap and pyldap.  I'm linking to pyldap because it's on GitHub, so GitHub should handle those links better.)

When an LDAP entry comes in during Syncrepl, the entry is accompanied by a Sync State Control, which includes an ASN.1 BER-encoded syncStateValue structure.  That structure contains an optional entry, named `cookie`.

The linked test script includes a binary string containing a structure where `cookie` is not present.  The breakage code is at https://github.com/pyldap/pyldap/blob/544b1e38f4b790d7e93448ed0d19f5906c0be31f/Lib/ldap/syncrepl.py#L138 :

```python
self.cookie = d[0].getComponentByName('cookie')
# …snip…
if self.cookie is not None:
    self.cookie = str(self.cookie)
```

**Comment by akkornel** [comment]
Until this is fixed somehow, I'm going to restrict the versions of pyasn1 I support.

**Comment by etingof** [comment]
I do not think this is a pyasn1 problem. 

That exception means that you are trying to use a non-initialized field (`cookie`) from the data structure (`syncStateValue`). You can see that if you call `.prettyPrint()`:

    ...
     print('cookie is', asn1_decoded[0].prettyPrint())

The output would be:

    pyasn1 version is 0.3.2
    state is 1
    uuid is e1d57f4e-234f-1035-97a2-4d5606180c6f
    cookie is syncStateValue:
     state='add'
     entryUUID=0xe1d57f4e234f103597a24d5606180c6f
     cookie=<no value>

That happens because the  `cookie` field is optional so it can legitimately have no value.

A fix could be to check that the optional values are present before using it:

    if decoded_cookie.hasValue():
        print(decoded_cookie)

Or pre-initialize the `cookie` field to some sane default:

    class syncStateValue(univ.Sequence):
        componentType = namedtype.NamedTypes(
            namedtype.NamedType('state', syncStateOp()),
            namedtype.NamedType('entryUUID', syncUUID()),
            namedtype.OptionalNamedType('cookie', syncCookie(''))
    )

So even if the `cookie` value is never picked up from the serialized form, the field object would be always initialized.

**Comment by akkornel** [comment]
Hi @etingof, thanks *very* much for the detailed information!  That is extremely helpful.

I am going to look at the `ldap.syncrepl` code, to work in the suggestions you made.  And, at the same time, I have to update the Python-LDAP test framework, because right now it is not set up for testing Syncrepl (for example, OpenLDAP configuration needs some changes).

I'll post updates to the Python-LDAP mailing list.  Thanks again!

**Comment by etingof** [comment]
Just for posterity, the following modification of your reproducer fixes the crash.

I am also trying to push similar fix to both python-ldap and pyldap.

```
#!/bin/env python3

import pyasn1
from pyasn1.type import constraint, namedtype, namedval, univ
from pyasn1.codec.ber.decoder import decode
from uuid import UUID

# These come from Python-LDAP's syncrepl module.
# They're definitions for pyasn1 to understand what it's parsing.

class syncUUID(univ.OctetString):
    subtypeSpec = constraint.ValueSizeConstraint(16,16)

class syncCookie(univ.OctetString):
    pass

class syncStateOp(univ.Enumerated):
    namedValues = namedval.NamedValues(
        ('present', 0),
        ('add', 1),
        ('modify', 2),
        ('delete', 3)
    )
    subtypeSpec = univ.Enumerated.subtypeSpec + constraint.SingleValueConstraint(0,1,2,3)

class syncStateValue(univ.Sequence):
    componentType = namedtype.NamedTypes(
        namedtype.NamedType('state', syncStateOp()),
        namedtype.NamedType('entryUUID', syncUUID()),
        namedtype.OptionalNamedType('cookie', syncCookie())
    )

# Now, let's take our ASN.1 and decode it.

asn1_binary = b'0\x15\n\x01\x01\x04\x10\xe1\xd5\x7fN#O\x105\x97\xa2MV\x06\x18\x0co'
asn1_decoded = decode(asn1_binary,
    asn1Spec = syncStateValue()
)

# Break out each item from the decoded ASN.1

decoded_state = asn1_decoded[0].getComponentByName('state')
decoded_uuid = asn1_decoded[0].getComponentByName('entryUUID')
decoded_cookie = asn1_decoded[0].getComponentByName('cookie')
if decoded_cookie is None or not decoded_cookie.hasValue():
    decoded_cookie = None

# Now, try to print it.
# Note that PyASN.1 is lazy, so it doesn't evaluate everything until now.

print('pyasn1 version is', pyasn1.__version__)
print('state is', decoded_state)
print('uuid is', UUID(bytes=bytes(decoded_uuid)))
print('cookie is', str(decoded_cookie))
```

**Comment by akkornel** [comment]
That's awesome.  Thank for _very_ much for the work!
