### ISSUE TITLE
demo.py, referenced in README, is not present in master

### ISSUE THREAD

**Issue by matthewh** [akkornel/syncrepl#22]
Though I found it in the v.90 tag.

**Comment by akkornel** [comment]
I see what happened.  Originally, I wrote up demo.py as a small thing.  That script was later enhanced, and changed to the `syncrepl-client` script that gets installed by `setup.py`/pip as a script.  So, for the latest and greatest, take a look at `syncrepl-client` in the root of the repo.

I'll push a docs update shortly!

**Comment by matthewh** [comment]
Thanks!
